from ttkbootstrap.themes import user

from sd_cpp_gui.infrastructure.logger import get_logger

logger = get_logger(__name__)

_THEME_DEFINITIONS = {
    "sdcpp": {
        "type": "light",
        "colors": {
            "primary": "#31849B",
            "secondary": "#99895E",
            "success": "#769348",
            "info": "#4A7A9F",
            "warning": "#C79636",
            "danger": "#BD4C4F",
            "light": "#DBD4BD",
            "dark": "#3D4247",
            "bg": "#F2EFE4",
            "fg": "#525D66",
            "selectbg": "#DED7C5",
            "selectfg": "#2C353C",
            "border": "#D1CBB8",
            "inputfg": "#4A555E",
            "inputbg": "#EBE7DB",
            "active": "#CFC8B6",
        },
    },
    "sdcpp_fog": {
        "type": "light",
        "colors": {
            "primary": "#455A64",
            "secondary": "#90A4AE",
            "success": "#5C946E",
            "info": "#548CA8",
            "warning": "#D4A353",
            "danger": "#C45B5E",
            "light": "#FFFFFF",
            "dark": "#263238",
            "bg": "#F0F2F5",
            "fg": "#37474F",
            "selectbg": "#CFD8DC",
            "selectfg": "#263238",
            "border": "#D1D9E0",
            "inputfg": "#37474F",
            "inputbg": "#FFFFFF",
            "active": "#E3E8EE",
        },
    },
    "sdcpp_purple": {
        "type": "light",
        "colors": {
            "primary": "#8F6EAF",
            "secondary": "#8C8691",
            "success": "#8FB390",
            "warning": "#E0C097",
            "danger": "#D68C8C",
            "info": "#9E8BA8",
            "light": "#F9F5FB",
            "dark": "#4A454F",
            "bg": "#FAF9F6",
            "fg": "#615B52",
            "selectbg": "#EBD9F2",
            "selectfg": "#4A454F",
            "border": "#E6DEEB",
            "inputfg": "#595261",
            "inputbg": "#FFFFFF",
            "active": "#E4D4EB",
        },
    },
    "sdcpp_aether": {
        "type": "light",
        "colors": {
            "primary": "#5B96B8",
            "secondary": "#94A3B8",
            "success": "#76B089",
            "info": "#7AC1E4",
            "warning": "#E0C382",
            "danger": "#D6787B",
            "light": "#F8FAFC",
            "dark": "#334155",
            "bg": "#F4F7F9",
            "fg": "#475569",
            "selectbg": "#D6E4ED",
            "selectfg": "#1E293B",
            "border": "#DAE1E8",
            "inputfg": "#334155",
            "inputbg": "#FFFFFF",
            "active": "#E2E8F0",
        },
    },
    "sdcpp_arctic": {
        "type": "light",
        "colors": {
            "primary": "#8AB6D6",
            "secondary": "#E6EBF0",
            "success": "#9BCFB8",
            "info": "#A8D8EA",
            "warning": "#F2D096",
            "danger": "#E8A0A0",
            "light": "#FFFFFF",
            "dark": "#4A5568",
            "bg": "#FFFFFF",
            "fg": "#5F6C7B",
            "selectbg": "#F0F8FF",
            "selectfg": "#2D3748",
            "border": "#F0F4F8",
            "inputfg": "#4A5568",
            "inputbg": "#FAFBFC",
            "active": "#F5F9FC",
        },
    },
    "sdcpp_arctic_pro": {
        "type": "light",
        "colors": {
            "primary": "#0065FF",
            "secondary": "#5E6C84",
            "success": "#36B37E",
            "info": "#00B8D9",
            "warning": "#FFAB00",
            "danger": "#FF5630",
            "light": "#EBECF0",
            "dark": "#172B4D",
            "bg": "#FFFFFF",
            "fg": "#172B4D",
            "selectbg": "#DEEBFF",
            "selectfg": "#FFFFFF",
            "border": "#DFE1E6",
            "inputfg": "#091E42",
            "inputbg": "#FAFBFC",
            "active": "#B3D4FF",
        },
    },
    "sdcpp_arctic_v2": {
        "type": "light",
        "colors": {
            "primary": "#0065FF",
            "secondary": "#6B778C",
            "success": "#36B35C",
            "info": "#65A8FF",
            "warning": "#FFAB00",
            "danger": "#FF5630",
            "light": "#FDFDFD",
            "dark": "#172B4D",
            "bg": "#FFFFFF",
            "fg": "#172B4D",
            "selectbg": "#355A92",
            "selectfg": "#FFFFFF",
            "border": "#E7E7E7",
            "inputfg": "#091E42",
            "inputbg": "#FAFAFA",
            "active": "#EBECF0",
        },
    },
    "sdcpp_dark": {
        "type": "dark",
        "colors": {
            "primary": "#61AFEF",
            "secondary": "#5C6370",
            "success": "#98C379",
            "info": "#56B6C2",
            "warning": "#E5C07B",
            "danger": "#E06C75",
            "light": "#9E9E9E",
            "dark": "#181A1F",
            "bg": "#21252B",
            "fg": "#ECECEC",
            "selectbg": "#3E4451",
            "selectfg": "#FFFFFF",
            "border": "#181A1F",
            "inputfg": "#F8F8F8",
            "inputbg": "#1D2127",
            "active": "#353B45",
        },
    },
    "sdcpp_dark2": {
        "type": "dark",
        "colors": {
            "primary": "#529EAD",
            "secondary": "#636E72",
            "success": "#87B368",
            "info": "#5FA8D3",
            "warning": "#E0B069",
            "danger": "#D16669",
            "light": "#C6D8DD",
            "dark": "#151719",
            "bg": "#212529",
            "fg": "#DFE6E9",
            "selectbg": "#384047",
            "selectfg": "#FFFFFF",
            "border": "#343A40",
            "inputfg": "#E0E0E0",
            "inputbg": "#2B3035",
            "active": "#41484F",
        },
    },
    "sdcpp_midnight": {
        "type": "dark",
        "colors": {
            "primary": "#6B8AF0",
            "secondary": "#475569",
            "success": "#4ADE80",
            "info": "#38BDF8",
            "warning": "#FBBF24",
            "danger": "#F87171",
            "light": "#D0D1D1",
            "dark": "#0F172A",
            "bg": "#0B1120",
            "fg": "#E2E8F0",
            "selectbg": "#334155",
            "selectfg": "#FFFFFF",
            "border": "#1E293B",
            "inputfg": "#F1F5F9",
            "inputbg": "#151F32",
            "active": "#263549",
        },
    },
}

USER_THEMES = _THEME_DEFINITIONS

def register_themes() -> None:
    user.USER_THEMES.update(_THEME_DEFINITIONS)
    logger.info(f"Registered {len(_THEME_DEFINITIONS)} custom themes.")
